name: Build and Release
permissions:
  contents: write

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '25'

      - name: Build
        run: mvn clean package

      - name: Get version from pom.xml
        id: get_version
        shell: bash
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
      
      - name: Prepare release
        shell: bash
        run: |
          mkdir -p release
          cp target/IncomeUtility-${{ steps.get_version.outputs.VERSION }}.jar \
             release/Income-Utility-${{ steps.get_version.outputs.VERSION }}.jar

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: Income Utility v${{ steps.get_version.outputs.VERSION }}
          files: release/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
